// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmICMF8wbescrkwOc6GUIl9dYxfKa1D4o',
    appId: '1:122677649342:web:90c824dd0d97d196a263ef',
    messagingSenderId: '122677649342',
    projectId: 'exam-f2ddf',
    authDomain: 'exam-f2ddf.firebaseapp.com',
    storageBucket: 'exam-f2ddf.appspot.com',
    measurementId: 'G-B9HJZWLKM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGS51NdSbwxnL0H5RWpi0LYjTCcE86RVA',
    appId: '1:122677649342:android:2108021a005695bca263ef',
    messagingSenderId: '122677649342',
    projectId: 'exam-f2ddf',
    storageBucket: 'exam-f2ddf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcu9zVaBHZJ6uwI6S9ekO42Gr53z3NyDw',
    appId: '1:122677649342:ios:7d8c0b1c5f3228cca263ef',
    messagingSenderId: '122677649342',
    projectId: 'exam-f2ddf',
    storageBucket: 'exam-f2ddf.appspot.com',
    iosBundleId: 'com.example.storeApi',
  );
}
